revert to sphinx-action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -51,39 +51,26 @@ jobs:
       run: coverage run -m pytest tests
 
     - name: Combine all coverage results
-      run: |
-        coverage combine
-        coverage report
+      run: coverage combine
+
+    - run: coverage report
+
     - name: Coveralls Parallel
       run: coveralls --service=github
       env:
         GITHUB_TOKEN: ${{ secrets.github_token }}
         COVERALLS_FLAG_NAME: python-${{ matrix.version }}
         COVERALLS_PARALLEL: true
-
-    # Publish built docs to gh-pages branch.
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/NLESC-JCER/QMCTorch.git --branch gh-pages --single-branch gh-pages
-        jupyter nbconvert --to notebook --execute docs/notebooks/sampling.ipynb
-        cp -r docs/_build/html/* gh-pages/
-        cd gh-pages
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-      env:
-        CONDA_PREFIX: /usr/share/miniconda
-    - name: Push changes
-      uses: ad-m/github-push-action@master
+    # Standard drop-in approach that should work for most people.
+    - uses: ammaraskar/sphinx-action@master
       with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+        docs-folder: "docs/"
+    # Great extra actions to compose with:
+    # Create an artifact of the html output.
+    - uses: actions/upload-artifact@v1
+      with:
+        name: DocumentationHTML
+        path: docs/_build/html/
     
 
   finish:
@@ -95,4 +82,23 @@ jobs:
         with:
           github-token: ${{ secrets.github_token }}
           parallel-finished: true
-
+      # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/NLESC-JCER/QMCTorch.git --branch gh-pages --single-branch gh-pages
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
