try without sphinx-action

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,17 +27,16 @@ jobs:
     - name: Install essential
       run: |
         sudo apt update
-        sudo apt install build-essential
+        sudo apt install build-essential pandoc
     - name: Install conda packages
       run: |
         conda install -c anaconda cmake
         conda install rdkit mpi4py h5py pytorch==2.0.0 torchvision==0.15.0 cpuonly -c pytorch -c conda-forge
         conda install -c conda-forge libstdcxx-ng
         conda install -c anaconda gxx_linux-64
-        conda install pandoc
 
     - name: Install the package
-      run: python -m pip install .[test,hpc]
+      run: python -m pip install .[test,hpc,doc]
       env:
         CONDA_PREFIX: /usr/share/miniconda
 
@@ -62,18 +61,30 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.github_token }}
         COVERALLS_FLAG_NAME: python-${{ matrix.version }}
         COVERALLS_PARALLEL: true
-    # Standard drop-in approach that should work for most people.
-    - uses: ammaraskar/sphinx-action@master
-      with:
-        docs-folder: "docs/"
-      env:
-        CONDA_PREFIX: /usr/share/miniconda
-    # Great extra actions to compose with:
-    # Create an artifact of the html output.
-    - uses: actions/upload-artifact@v1
-      with:
-        name: DocumentationHTML
-        path: docs/_build/html/
+
+      # Publish built docs to gh-pages branch.
+      # ===============================
+      - name: Commit documentation changes
+        run: |
+          git clone https://github.com/NLESC-JCER/QMCTorch.git --branch gh-pages --single-branch gh-pages
+          jupyter nbconvert --to notebook --execute docs/notebooks/sampling.ipynb
+          cp -r docs/_build/html/* gh-pages/
+          cd gh-pages
+          touch .nojekyll
+          git config --local user.email "action@github.com"
+          git config --local user.name "GitHub Action"
+          git add .
+          git commit -m "Update documentation" -a || true
+          # The above command will fail if no changes were present, so we ignore
+          # that.
+        env:
+          CONDA_PREFIX: /usr/share/miniconda
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          branch: gh-pages
+          directory: gh-pages
+          github_token: ${{ secrets.GITHUB_TOKEN }}
     
 
   finish:
@@ -85,23 +96,4 @@ jobs:
         with:
           github-token: ${{ secrets.github_token }}
           parallel-finished: true
-      # Publish built docs to gh-pages branch.
-      # ===============================
-      - name: Commit documentation changes
-        run: |
-          git clone https://github.com/NLESC-JCER/QMCTorch.git --branch gh-pages --single-branch gh-pages
-          cp -r docs/_build/html/* gh-pages/
-          cd gh-pages
-          touch .nojekyll
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add .
-          git commit -m "Update documentation" -a || true
-          # The above command will fail if no changes were present, so we ignore
-          # that.
-      - name: Push changes
-        uses: ad-m/github-push-action@master
-        with:
-          branch: gh-pages
-          directory: gh-pages
-          github_token: ${{ secrets.GITHUB_TOKEN }}
+
